#!/usr/bin/env python3
"""
Validate that JSON schemas generated by Spectra conform to JSON Schema 2020-12.

Usage:
    python validate_json_schema.py <schema.json> [schema2.json ...]
    python validate_json_schema.py schemas/*.json

Requirements:
    pip install jsonschema>=4.0.0
"""

import json
import sys
from pathlib import Path

try:
    import jsonschema
    from jsonschema import Draft202012Validator
except ImportError:
    print("Error: jsonschema library not found.")
    print("Install it with: pip install jsonschema>=4.0.0")
    sys.exit(1)


def get_schema_version(schema):
    """Determine JSON Schema version from $schema field"""
    schema_uri = schema.get("$schema", "")

    if "2020-12" in schema_uri:
        return "2020-12"
    elif "2019-09" in schema_uri:
        return "2019-09"
    elif "draft-07" in schema_uri:
        return "draft-07"
    elif "draft-06" in schema_uri:
        return "draft-06"
    elif "draft-04" in schema_uri:
        return "draft-04"
    else:
        return "unknown"


def load_json_file(filepath):
    """Load JSON from a file"""
    try:
        with open(filepath, 'r') as f:
            return json.load(f)
    except FileNotFoundError:
        raise Exception(f"File not found: {filepath}")
    except json.JSONDecodeError as e:
        raise Exception(f"Invalid JSON: {e}")


def validate_schema(schema_path):
    """
    Validate a Spectra-generated JSON schema.

    Checks:
    1. Schema has $schema field pointing to 2020-12
    2. Schema is valid according to JSON Schema 2020-12 meta-schema

    Returns:
        True if valid, False otherwise
    """
    print(f"\n{'='*70}")
    print(f"Validating: {schema_path}")
    print(f"{'='*70}")

    # Load the schema
    try:
        schema = load_json_file(schema_path)
    except Exception as e:
        print(f"❌ Failed to load schema: {e}")
        return False

    # Check 1: Verify $schema field exists
    if "$schema" not in schema:
        print(f"❌ Schema missing $schema field")
        return False

    schema_uri = schema.get("$schema", "")
    version = get_schema_version(schema)

    # Check 2: Verify it's JSON Schema 2020-12
    if version != "2020-12":
        print(f"❌ Schema does not declare JSON Schema 2020-12")
        print(f"   Found: {schema_uri} (version: {version})")
        print(f"   Expected: https://json-schema.org/draft/2020-12/schema")
        return False
    else:
        print(f"✅ Schema declares: {schema_uri}")

    # Check 3: Validate schema structure against meta-schema
    try:
        Draft202012Validator.check_schema(schema)
        print(f"✅ Schema is valid JSON Schema 2020-12")
    except jsonschema.SchemaError as e:
        print(f"❌ Schema validation failed: {e.message}")
        if e.path:
            print(f"   Path: {list(e.path)}")
        if e.schema_path:
            print(f"   Schema path: {list(e.schema_path)}")
        return False

    # Display schema info
    print(f"\n📋 Schema details:")
    schema_type = schema.get('type', 'any')
    print(f"   Type: {schema_type}")

    if 'properties' in schema:
        props = list(schema['properties'].keys())
        if len(props) <= 5:
            print(f"   Properties: {props}")
        else:
            print(f"   Properties: {props[:5]} ... ({len(props)} total)")

    if 'required' in schema:
        req = schema['required']
        if len(req) <= 5:
            print(f"   Required: {req}")
        else:
            print(f"   Required: {req[:5]} ... ({len(req)} total)")

    if 'enum' in schema:
        enum = schema['enum']
        if len(enum) <= 5:
            print(f"   Enum: {enum}")
        else:
            print(f"   Enum: {enum[:5]} ... ({len(enum)} values)")

    if 'oneOf' in schema:
        print(f"   OneOf: {len(schema['oneOf'])} alternatives")

    if 'items' in schema:
        print(f"   Items: {schema['items'].get('type', 'complex')}")

    return True


def main():
    if len(sys.argv) < 2:
        print("Usage: python validate_json_schema.py <schema.json> [schema2.json ...]")
        print("\nValidates that JSON schemas conform to JSON Schema 2020-12 specification.")
        print("\nExample:")
        print("  python validate_json_schema.py my_schema.json")
        print("  python validate_json_schema.py schemas/*.json")
        sys.exit(1)

    print("="*70)
    print("JSON Schema 2020-12 Validator")
    print("="*70)

    all_valid = True
    total_schemas = len(sys.argv) - 1
    valid_count = 0

    for schema_file in sys.argv[1:]:
        if validate_schema(schema_file):
            valid_count += 1
        else:
            all_valid = False

    # Summary
    print(f"\n{'='*70}")
    print(f"Summary: {valid_count}/{total_schemas} schemas valid")
    print(f"{'='*70}")

    if all_valid:
        print("✅ All schemas are valid JSON Schema 2020-12!")
        sys.exit(0)
    else:
        print("❌ Some schemas failed validation")
        sys.exit(1)


if __name__ == "__main__":
    main()
